#! /usr/bin/env bash

# You need to tweak this script to your needs
set -o errexit
set -o nounset
set -o pipefail

HOST=$1
KEY_URL=$2
TG_TOKEN=$3
TG_ID=$4

parted --script /dev/sda \
mklabel gpt \
mkpart "BOOT" fat32  1MiB  512MiB \
mkpart "NIXOS" ext4 512MiB 100% \
set 1 esp on  

mkfs.fat -F32 /dev/sda1
mkfs.ext4 -F /dev/sda2

mkdir /mnt
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

[[ -n "$2" ]] && mkdir -p /mnt/var/lib/age/ && curl -sLo /mnt/var/lib/age/sshkey "$KEY_URL"


mkdir -p /mnt/{etc,tmp}
touch /mnt/etc/NIXOS

nix build --store /mnt --profile /mnt/nix/var/nix/profiles/system  \
github:mlyxshi/flake#nixosConfigurations.$HOST.config.system.build.toplevel \
--extra-trusted-public-keys "cache.mlyxshi.com:qbWevQEhY/rV6wa21Jaivh+Lw2AArTFwCB2J6ll4xOI=" \
--extra-substituters "http://cache.mlyxshi.com" -v

NIXOS_INSTALL_BOOTLOADER=1 nixos-enter --root /mnt -- /run/current-system/bin/switch-to-configuration boot

for i in /etc/ssh/ssh_host_*; do cp $i /mnt/etc/ssh; done

[[ -n "$3" && -n "$4" ]] && curl -X POST "https://api.telegram.org/bot$TG_TOKEN/sendMessage" -d chat_id=$TG_ID -d text="<b>Install NixOS Completed</b>%0A$HOST" -d parse_mode=html

reboot