name: build kexec
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux

    - run: |
        nix build .#nixosConfigurations.kexec-x86_64.config.system.build.kexec --out-link upload1
    
    - run: |
        nix build .#nixosConfigurations.kexec-aarch64.config.system.build.kexec --out-link upload2

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          upload1/*
          upload2/*