name: build kexec
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux

    - run: |
        nix build .#nixosConfigurations.kexec-x86_64.config.system.build.kexec --out-link buildout1
        cp -Lr --no-preserve=all buildout1 artifact
    
    - run: |
        nix build .#nixosConfigurations.kexec-aarch64.config.system.build.kexec --out-link buildout2
        cp -Lr --no-preserve=all buildout2 artifact
   
    - run: |
        ls -alh artifact

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          artifact/*