name: build kexec
on: [ workflow_dispatch,push ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: docker/setup-qemu-action@master
    - uses: nixbuild/nix-quick-install-action@master
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
          trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.garnix.io https://cache.nixos.org/
    
    - run: cp -Lr --no-preserve=all $(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-x86_64.config.system.build.kexec) artifact1   
    - run: cp -Lr --no-preserve=all $(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-aarch64.config.system.build.kexec) artifact2

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          artifact1/*
          artifact2/*