name: build kexec
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          trusted-public-keys = mlyxshi.cachix.org-1:yc7GPiryyBn0HfiCXdmO1ECWKBhfwrjdIFnRSA4ct7s= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
          substituters = https://mlyxshi.cachix.org https://cache.garnix.io
    
    - uses: cachix/cachix-action@v12
      with:
        name: mlyxshi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: |
        nix build .#nixosConfigurations.kexec-x86_64.config.system.build.kexec --out-link buildout1
        cp -Lr --no-preserve=all buildout1 artifact1
    
    - run: |
        nix build .#nixosConfigurations.kexec-aarch64.config.system.build.kexec --out-link buildout2
        cp -Lr --no-preserve=all buildout2 artifact2

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          artifact1/*
          artifact2/*